# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kierunek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('yearbased', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Stopien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('semestr', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eMail', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wydzial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('kierunek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Kierunek')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='wydzial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Wydzial'),
        ),
        migrations.AddField(
            model_name='kierunek',
            name='stopien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Stopien'),
        ),
    ]
